### ISSUE TITLE
ADD about website

### ISSUE THREAD

**Issue by nysteo** [AnubisLMS/Anubis#119]
Ideally, the Marketing/Landing website should be separate from the Anubis web application.

- [ ] Setup Directory with Gatsby, material-ui
- [ ] Landing Page
- [ ] Features Page
- [ ] Feature Page
- [ ] Blog Page
- [ ] How to Contribute Page
- [ ] Contact Us Page
- [ ] Migrate blog from web to about

**Comment by wabscale** [comment]
https://github.com/AnubisLMS/AnubisWebsite
