### ISSUE TITLE
ADD Show diff between the expected output and the actual output in the autograder

### ISSUE THREAD

**Issue by PIG208** [AnubisLMS/Anubis#254]
**Is your feature request related to a problem? Please describe.**
The autograder integrated for the students only shows the expected output and the student output in plain text. This is not informative enough and requires extra work for students to compute the diff manually (especially when it's subtle).

**Describe the solution you'd like**
The outputs should be kept in a separate text box, with the diff shown. [react-diff-view](https://www.npmjs.com/package/react-diff-view) is a good candidate package for implementing this feature.

**Comment by wabscale** [comment]
This is a really great idea, thank you for suggesting it. Would you like to tackle this yourself, or have someone from the Anubis team work on it?

We are in the middle of a full UI redesign at the moment, so we'll need to see when it makes sense to add this. @nysteo would you be able to fix this into your UI redesign.
