### ISSUE TITLE
FIX the "we're on github" link is still pointing to GusSand/Anubis

### ISSUE THREAD

**Issue by wabscale** [AnubisLMS/Anubis#300]
https://github.com/anubislms/Anubis/blob/40a12933877df7f39dd75ca26148858774fcda7b/old-web/src/Components/Navigation/Nav.jsx#L34-L46

**Comment by efaraz27** [comment]
Hi i would like to take this task

**Comment by wabscale** [comment]
You've got it. The link in the new beta UI may also need to be updated. (the new web ui is in under the web directory)

**Comment by efaraz27** [comment]
2 questions before i start
1. i see a typo on line 45. "We&apos;re on Github" should be "we're on github" ?
2.  what should be new link point to?

**Comment by AlpacaMax** [comment]
1. We can go with "We're on Github". It doesn't really matter
2. The new link should point to this repository, which is `https://github.com/AnubisLMS/Anubis`. We recently moved this repo under this organization so we need to update the link of this button

**Comment by efaraz27** [comment]
Sent the PR Request :)
