### ISSUE TITLE
Need a way in the admin page to delete a repo!

### ISSUE THREAD

**Issue by GusSand** [AnubisLMS/Anubis#309]
To delete a repo in a bad state here's is the current way:

Anubis -> Repos -> delete

It would be really great if we added this in the admin page as well:

Assignments -> Assingment Name -> View Repos > PLEASE ADD DELETE BUTTON HERE TOO!  😃 

cheers
G

**Comment by wabscale** [comment]
This is implemented in https://github.com/AnubisLMS/Anubis/commit/e90f7b1770f109d70490a9f1324c81e36832b70c. I'm going to wait to roll this out until tomorrow when there is less people on the system.

**Comment by wabscale** [comment]
This is now deployed. There is a delete button with a dialog, and and an extra confirmation on the assignment setting page
