### ISSUE TITLE
ADD Allow TAs to open an IDE for student's repo

### ISSUE THREAD

**Issue by AlpacaMax** [AnubisLMS/Anubis#310]
Currently we can view a student's IDE when the student has one open. We want to be able to open an IDE for students' repos for debugging and grading purpose. Changes made in this IDE should be forbidden to be pushed to the student's repo.

**Comment by GusSand** [comment]
I love this feature!

 

From: Maxwell Yang ***@***.***> 
Sent: Wednesday, November 17, 2021 11:38 AM
To: AnubisLMS/Anubis ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AnubisLMS/Anubis] ADD Allow TAs to open an IDE for student's repo (Issue #310)

 

Currently we can view a student's IDE when the student has one open. We want to be able to open an IDE for students' repos for debugging and grading purpose. Changes made in this IDE should be forbidden to be pushed to the student's repo.

**Comment by AlpacaMax** [comment]
Yining proposes this feature more than 2 weeks ago in the slack. Thought I should add this card just in case we forget it.
