### ISSUE TITLE
BUG Issues I found with the new frontend

### ISSUE THREAD

**Issue by AlpacaMax** [AnubisLMS/Anubis#314]
1. All of the submissions are listed as late submission even though homework4 hasn't due yet. Also it says invalid date as the submission date.
![Screen Shot 2021-11-29 at 6 06 44 PM](https://user-images.githubusercontent.com/31149339/143957564-ddfba9c0-9bcc-4f94-8f6f-c6954b41444a.png)
2. The heading of the "Lecture" tab is stylistically inconsistent with the ones in other tabs.
![Screen Shot 2021-11-29 at 6 07 11 PM](https://user-images.githubusercontent.com/31149339/143957786-34319742-7936-4e65-a1b3-f631bf6bb198.png)
![Screen Shot 2021-11-29 at 6 07 17 PM](https://user-images.githubusercontent.com/31149339/143958205-03cc704c-6064-4f5e-a3d7-f329a6f84729.png)

3. The expand button on each individual submission page does not work. For this one, the one on "build" does nothing. The one on "ls" gets a popup but shows nothing in expected and actual results.
![Screen Shot 2021-11-29 at 6 12 37 PM](https://user-images.githubusercontent.com/31149339/143958008-45a202b9-353a-4ef8-a565-0672c6bf9ccc.png)
![Screen Shot 2021-11-29 at 6 12 44 PM](https://user-images.githubusercontent.com/31149339/143958012-444575e7-1187-46a3-a8dc-e54b8df0e983.png)

4. When you click into a course and scroll down. The "Name" and "Email" labels in the "Instructors / Teaching Assistants" part does not hide when it should be covered by the heading part.
![Screen Shot 2021-11-29 at 6 25 49 PM](https://user-images.githubusercontent.com/31149339/143959134-5b730a69-4f42-4a0e-b33c-24f741236cb8.png)

Overall I think the new frontend looks really awesome! Good job for the frontend team!

**Comment by nysteo** [comment]
I am on it!

**Comment by AlpacaMax** [comment]
5. The `view repo` button on each assignment page does not work
