### ISSUE TITLE
ADD something to be able to disable a specific user

### ISSUE THREAD

**Issue by wabscale** [AnubisLMS/Anubis#318]
This will likely be some field we add to the User table, then add some check in the [anubis.utils.auth.get_current_user](https://github.com/AnubisLMS/Anubis/blob/04ebf040989f273f4d6014142370379012a57eec/api/anubis/utils/auth/user.py#L14) function.

Disabling a specific user is definitely going to stay at the superuser permission level.

**Comment by AlpacaMax** [comment]
What do you mean by disabling a user? And why we need to do that?

**Comment by wabscale** [comment]
I mean flipping a switch and making it so that a specific user cannot sign into Anubis.

We have not had any issues of abuse *yet*. I would like to have this feature ready before we need it.
