### ISSUE TITLE
BUG course page saying all assignments are not visible (when some are and some are not)

### ISSUE THREAD

**Issue by wabscale** [AnubisLMS/Anubis#343]
![Screenshot 2022-02-20 at 18-19-38 Anubis LMS](https://user-images.githubusercontent.com/36013983/154868784-75901ec2-1c2e-4216-b797-a07f35da2c09.png)

**Comment by wabscale** [comment]
It is something to do with the AssignmentItem component on the course page `/course?courseId=<course id hash>`. The AssignmentItem component is likely just missing the `visible_to_students` field

- Course Page: https://github.com/AnubisLMS/Anubis/blob/master/web/src/pages/core/public/Course/Course.jsx
- AssignmentItem Component: https://github.com/AnubisLMS/Anubis/blob/master/web/src/components/core/AssignmentItem/AssignmentItem.jsx

**Comment by synoet** [comment]
Please make sure to follow the contribution guidelines established here: https://github.com/AnubisLMS/Anubis/blob/master/.github/CONTRIBUTING.md
