### ISSUE TITLE
CHG More verbose routing

### ISSUE THREAD

**Issue by PIG208** [AnubisLMS/Anubis#345]
Update location history upon opening a modal, switching pages within a paginated view, entering search queries. This will help facilitate the usage of the back button and provide more variations of sharable links.

**Comment by wabscale** [comment]
I believe I got everything in this here https://github.com/AnubisLMS/Anubis/commit/e7b1336ddfdfeb087b0d66284a0d0117b4cf34d5

Reopen this if there is anything that I missed
