### ISSUE TITLE
Question - Do test cases run in parallel?

### ISSUE THREAD

**Issue by nt591** [AnubisLMS/Anubis#346]
My class is using Anubis for assignments. Many students are running into an issue where one test case on an assignment fails with a weird error message. I believe test case N is writing a file and test case N+1 is reading the file. It seems N+1 runs before N, causing `cat` to fail. Can you confirm or deny that tests are run in parallel rather than sequentially?

**Comment by wabscale** [comment]
Tests run in sequence, not in parallel. This seems like a question you should probably direct to your TAs.
