### ISSUE TITLE
CHG Allow the user to open autograde results in a new tab

### ISSUE THREAD

**Issue by PIG208** [AnubisLMS/Anubis#349]
Allow the user to open autograde results in a new tab.

This saves some time from requiring the grader to reload the autograde results page after finishing viewing one submission.

**Comment by wabscale** [comment]
Would this mean when you click on a student on the `admin/autograde/assignment/<assignment id>` page it opens in a new tab?

**Comment by PIG208** [comment]
> Would this mean when you click on a student on the `admin/autograde/assignment/<assignment id>` page it opens in a new tab?

Yes. Another problem with the current approach is that the current location is not pushed to the browser history.

**Comment by wabscale** [comment]
Oh ok I see. That should be easy to handle.

**Comment by PIG208** [comment]
Thanks!
