### ISSUE TITLE
ADD Documentation for Anubis CLI and Grading IDE

### ISSUE THREAD

**Issue by PIG208** [AnubisLMS/Anubis#350]

**Comment by wabscale** [comment]
We've needed this for a while now. The hope that I've had is that we could put some kind of a knowledge base or something on the website itself. We could just do markdown pages and stuff like how the blog is.

What were you thinking for this?

**Comment by AlpacaMax** [comment]
Honestly I don't think Markdown is suitable for documentations. I think we can try gitbook or Read the Docs and just incrementally add stuff to it over time.

**Comment by PIG208** [comment]
I would say mkdocs looks pretty good. FastAPI for example uses it https://github.com/tiangolo/fastapi/tree/master/docs

**Comment by PIG208** [comment]
> Honestly I don't think Markdown is suitable for documentations. I think we can try gitbook or Read the Docs and just incrementally add stuff to it over time.

We can use some existing static site tools for doc so that we don't need to reinvent the wheels, but still need to write markdowns anyway.

**Comment by PIG208** [comment]
Closing because we are getting it in https://github.com/AnubisLMS/CLI.
