### ISSUE TITLE
ADD Privacy Policy Component 

### ISSUE THREAD

**Issue by synoet** [AnubisLMS/Anubis#351]
Create a component that has a privacy policy with a checkbox stating that they agree.

https://docs.google.com/document/d/13-rC9s-4KMWpHr2wMnaxu4WIxdY7fwUf31DxHNQ9Les/mobilebasic

**Comment by synoet** [comment]
Please make sure to follow the contribution guidelines layed out here: https://github.com/AnubisLMS/Anubis/blob/master/.github/CONTRIBUTING.md

**Comment by wabscale** [comment]
https://github.com/AnubisLMS/Anubis/commit/c449351a31fa7136ac7dd552b732a4ce86ab955e
