### ISSUE TITLE
CHG update lectures public page to be new layout

### ISSUE THREAD

**Issue by synoet** [AnubisLMS/Anubis#352]
https://anubis.osiris.services/lectures is still following the old layout we used on the old web.

Update it to have the same layout and formatting as the other pages.

You can find reference for this on any of the other public pages. They have all been re-worked.

**Comment by synoet** [comment]
Please follow the contribution guidelines stated here: https://github.com/AnubisLMS/Anubis/blob/master/.github/CONTRIBUTING.md

**Comment by AaronBinChen** [comment]
Closing the issue because solution was committed to master branch by John.

**Comment by AaronBinChen** [comment]
Closing the issue because solution was committed to master branch by John.
