### ISSUE TITLE
CHG convert api typing to py3.10 standards

### ISSUE THREAD

**Issue by wabscale** [AnubisLMS/Anubis#360]
There are a bunch of things that have changed with type annotations in python 3.10 that we should move the api to. These changes primarily involve things like using `list` instead of `typing.List` and `dict` instead of `typing.Dict`. 

We don't need to do this all at once. We can do one file or one module at a time.

https://docs.python.org/3/library/typing.html

**Comment by sp6370** [comment]
Hi @wabscale! I would like to take this issue up.

**Comment by wabscale** [comment]
Sure. I already did a lot of it with just doing find and replace, but I'm sure I missed things. Let me know if you have any questions

**Comment by sp6370** [comment]
> Sure. I already did a lot of it with just doing find and replace, but I'm sure I missed things. Let me know if you have any questions

I am trying to set up the dev environment on my M1 mac. I am running into issues with python. I am trying to launch the project using the make file, however, the API server is not getting started.

How can I check if the virtual environment required for API is getting set up? 

<img width="940" alt="image" src="https://user-images.githubusercontent.com/26037101/163076690-5f4b06e0-c92d-4330-a36d-44ef348a1696.png">

**Comment by wabscale** [comment]
This is probably because the virtualenv for the api did not full initialize correctly. You can go to the api directory and do `rm -rf venv && make venv` to re-create it.

**Comment by wabscale** [comment]
@ravitejasssihl you can get started with this one.

**Comment by ravitejasssihl** [comment]
Hai @wabscale can you please give more details about this issue...

**Comment by ravitejasssihl** [comment]
Can you please tell in what all files I should make these changes.?

**Comment by ravitejasssihl** [comment]
@wabscale @sp6370 @jepst  this looks like its already finished ,all are replaced the issue is closed

**Comment by wabscale** [comment]
Yeah this is pretty much done. Please do not @ jepst randomly, he is a professor that uses Anubis and does not participate in development.

**Comment by ravitejasssihl** [comment]
can you pleas tell when it was closed?
