### ISSUE TITLE
FIX current version of theia does not work

### ISSUE THREAD

**Issue by wabscale** [AnubisLMS/Anubis#364]
Version v1.23.0 switched their socket implementation to socket.io. Whatever changed now does not respect nested websites. We're probably going to need to go through the PR in theia where this was introduced and fix it. 

https://github.com/eclipse-theia/theia/pull/10514

For now we're locking the theia versions to 1.22.1

**Comment by wabscale** [comment]
Ok so it looks like the theia people caught this and fixed this a few weeks ago, though it has not made it into a release yet: https://github.com/eclipse-theia/theia/pull/10858

It is due for theia `1.24.0` which is in a few days: https://github.com/eclipse-theia/theia/milestone/32

**Comment by ravitejasssihl** [comment]
Hi @wabscale ,Am intrested in contributing to solve this issue,can you please assign me this,It would be helpful.
Thank you

**Comment by wabscale** [comment]
This issue was actually solved a while back. They fixed the socket.io nesting stuff in 1.25.0. We are on 1.28.0 now:

https://github.com/AnubisLMS/IDE/blob/main/theia-base/latest.package.json#L19-L53
