### ISSUE TITLE
FIX longhorn backup server on digitalocean

### ISSUE THREAD

**Issue by wabscale** [AnubisLMS/Anubis#367]
longhorn nfs backup server is currently borked :(

**Comment by ravitejasssihl** [comment]
Hi @jepst  @wabscale  ,Am intrested in contributing to solve this issue,can you please assign me this,It would be helpful.
Thank you

**Comment by wabscale** [comment]
Hi, please dont @ jepst. He's a professor that uses Anubis, he doesnt participate in its development.

This issue can really only be solved by someone that has access to our digitalocean (so me and a few other maintainers).

If you are looking for an issue to pick up, these may be good ones to start:
- https://github.com/AnubisLMS/Anubis/issues/351
- https://github.com/AnubisLMS/Anubis/issues/360
- https://github.com/AnubisLMS/Anubis/issues/355

**Comment by ravitejasssihl** [comment]
Hai Brother,
Can you please assign me those issues?
Either #351,#355 or #360.
