### ISSUE TITLE
BUG submission page pagination is messed up if you go past end 

### ISSUE THREAD

**Issue by wabscale** [AnubisLMS/Anubis#370]
From: https://github.com/AnubisLMS/Anubis/issues/353

There is some off by one or bounds issue somewhere in the logic here. https://github.com/AnubisLMS/Anubis/blob/master/web/src/pages/core/public/Submissions/Submissions.jsx

**Comment by synoet** [comment]
fixed
https://github.com/AnubisLMS/Anubis/commit/a1d5b902e8415fb91d3e7d5c0d6c30db2b23dc8f
