### ISSUE TITLE
ADD column to superuser playground table for if docker is enabled

### ISSUE THREAD

**Issue by wabscale** [AnubisLMS/Anubis#400]
Add column for new `docker` row column with  mui icon to indicate if it is on or off.

Column definitions here: https://github.com/AnubisLMS/Anubis/blob/95139fc5492e76fdd20be0a6a65d4bd4f20dd347/web/src/pages/core/super/Playgrounds.jsx#L54-L101

**Comment by dolf321** [comment]
Hi @wabscale, created a PR for this, please review #449. 

Thanks!
