### ISSUE TITLE
CHG sort test results by name on submission page

### ISSUE THREAD

**Issue by wabscale** [AnubisLMS/Anubis#408]

**Comment by dolf321** [comment]
Hi @wabscale, I can take this up!

**Comment by wabscale** [comment]
Oh hey, this is way out of date. I already added a thing to do this. It basically assigns a specific order to the assignment tests: 

https://github.com/AnubisLMS/Anubis/blob/3fede7a9fe5e8efb022707e86424abcafc583ad7/api/anubis/models/__init__.py#L351

https://github.com/AnubisLMS/Anubis/blob/3fede7a9fe5e8efb022707e86424abcafc583ad7/api/anubis/lms/submissions.py#L266
