### ISSUE TITLE
ADD side-by-side answer/solution view

### ISSUE THREAD

**Issue by PIG208** [AnubisLMS/Anubis#419]
**Is your feature request related to a problem? Please describe.**
TAs can add solutions to the assignment, but they are only visible on the edit assignment page.

**Describe the solution you'd like**
It will be great if the solutions for each question appear by the side of students' submissions.

**Additional context**
OS midterm grading

**Comment by wabscale** [comment]
https://github.com/AnubisLMS/Anubis/pull/451
