### ISSUE TITLE
ADD UI for resending github collaboration invitation

### ISSUE THREAD

**Issue by PIG208** [AnubisLMS/Anubis#420]
**Is your feature request related to a problem? Please describe.**
When the collaboration invitation expires, the student needs to be added to their repo manually.

**Describe the solution you'd like**
Provide a way to let the student trigger a new invitation to be sent automatically.

**Additional context**
[campuswire](https://campuswire.com/c/GC0E420B5/feed/625)

**Comment by wabscale** [comment]
We can add a button for this, though this can also be done automatically.  I can add something to the end of day job that checks the repos for active assignments for missing collaborators.

**Comment by wabscale** [comment]
Half way there. The collaborators for all active assignments are now checked in the daily cleanup job.

https://github.com/AnubisLMS/Anubis/commit/7d5d7e910f3b6e633ba4224e978f903c449b0f18
https://github.com/AnubisLMS/Anubis/commit/7295b25094efa35a07afccea94a67eb33c87d01b

I'm not certain that a button is really necessary with these additions.
