### ISSUE TITLE
Question - "congratulations" but still displayed incomplete

### ISSUE THREAD

**Issue by yh4557** [AnubisLMS/Anubis#444]
When doing an assignment, I got a "Congratulations" after I finished everything but there was still an incomplete sign when the session ended. And it said that there is a task that doesn't exist failed.

Please tell me what to do. Thank you for your time and care! Take care!!

**Comment by wabscale** [comment]
Go ahead and take a look now. Turns out there was a hidden test that shouldn't have been there.
